name: Build QMK firmware
on: [push, workflow_dispatch]
jobs:
  gather-keyboards:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - uses: actions/checkout@v3
      with:
        repository: ${{ github.repository}}
        ref: ${{ github.ref }}
    - name: load config to env
      id: step_one
      run: |
        echo actions_config.json >> $GITHUB_OUTPUT
  build:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli
    strategy:
      fail-fast: false
      matrix:
# List of keymap json files to build
        file: "${{steps.step_one.outputs.config[*].keymap_json}}"
        

# End of json file list

    steps:

    - name: Checkout QMK
      uses: actions/checkout@v3
      with:
        repository: ${{env.config[*].repository}}
# Uncomment the following for develop branch
        ref: ${{env.config[*].branch}}
        submodules: true

    - name: Checkout userspace
      uses: actions/checkout@v2
      with:
        path: users/${{ github.actor }}

    - name: Build firmware
      run: qmk compile -j 8 "users/${{ github.actor }}/${{ matrix.file }}"

    - name: Archive firmware
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.file }}_${{ github.actor }}
        retention-days: 5
        path: |
          *.hex
          *.bin
          *.uf2
      continue-on-error: true
